---
- name: Configure database server
  hosts: db
  vars:
    postgresql_databases:
      - name: hello
        owner: hello
    postgresql_users:
      - name: hello
        pass: "{{ lookup('password', inventory_dir + '/hello_db_password') }}"
    postgresql_listen_addresses:
      - 0.0.0.0
    postgresql_pg_hba_custom:
      - { type: host, database: hello, user: hello, address: 0.0.0.0/0, method: "md5", comment: "" }
  roles:
    - role: ANXS.postgresql
